export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UPSTREAM_SERVICE_ERROR = 'UPSTREAM_SERVICE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
